### ISSUE TITLE
Downloaded repo doesn't build

### ISSUE THREAD

**Issue by JvandeKraats** [synercoder/FormsAuthentication#10]
When downloading the whole repo and opening the solution file in VS2017, it won't build because the TestImplementation.ReadCookie project doesn't know the UseBrowserLink method. I included a screenshot below.

![image](https://user-images.githubusercontent.com/7449547/59997566-b1c34480-965d-11e9-9412-e0e890d0c01b.png)

I've tried cleaning, rebuilding and restoring the nuget packages for the whole solution.

**Comment by synercoder** [comment]
Try again? I removed the browserlink in #11 . That was something visual studio used to make debugging easier. But it is no longer the way to go, and isn't important for the sample.

**Comment by JvandeKraats** [comment]
The build now succeeds, thanks for the fix.
