### ISSUE TITLE
Support for custom Ticket Version

### ISSUE THREAD

**Issue by lemoinem** [synercoder/FormsAuthentication#12]
Hello,

I need to do this, however, our ASP.Net 4.5 is using both a custom ticket Version. However, your serializer.deserializer (FormsAuthenticationCryptor's ConvertToBytes hardcodes it to 1 and ConvertToAuthenticationTicket ignores it) does not support this.

Is it something you would consider adding? I don't think it would be a major change. I would be ready to provide a PR.

**Comment by synercoder** [comment]
A PR is welcome

**Comment by synercoder** [comment]
Your PR is not forgotten, just haven't got around to it yet. Will finish it somewhere this week.
