### ISSUE TITLE
Support Core 3? Nuget says it needs to install lots of 2.0 dependencies

### ISSUE THREAD

**Issue by timavaza** [synercoder/FormsAuthentication#15]
When trying to add this nuget package to a new Core3 application, it lists a lot of 2.0 dependencies that apparently would need to be installed:
![image](https://user-images.githubusercontent.com/41233225/69700305-13b03a80-1125-11ea-81c2-17267d3a6546.png)

Scared to do so, as it might start dll hell...

**Comment by synercoder** [comment]
This library was build for net core 2.0. No testing was done on 3.0 yet. PRs are open if you want to port it to 3.0.

**Comment by timavaza** [comment]
I wish I could help with that, but i'm a complete beginner at the moment

**Comment by synercoder** [comment]
Well then, I did a thing.

https://www.nuget.org/packages/Synercoding.FormsAuthentication/3.1.0-alpha01

Currently build as alpha01, I dont expect any new bugs versus previous version, but please let me know if this version doesn't work for you.
