### ISSUE TITLE
Cookie decryption issue Core 3.1

### ISSUE THREAD

**Issue by danielarturo** [synercoder/FormsAuthentication#20]
I have been trying to integrate the component to my solution but it doesnt call the ConvertCookieToTicket method, in the sample project it works fine, but for some reason I cant identify it doesnt work when using my own login app in spite it seems to be configured just like the one you included in your sample, you can find my test proyecto in this link: 
[https://www.dropbox.com/s/j9t1vi3gp9go582/FormsAuthentication-update-netcore-3.rar?dl=0](url)

When running the solution try using this login: http://localhost:58499/

Any clue of what could be missing or wrong, thank you very much for your time and help

**Comment by synercoder** [comment]
Don't ask why (was too long ago when I molded the code for the last time), by comparing the setcookie & Presupuestos web.config files and the power of elimination... I present you:

<pre>
&lt;httpRuntime <strong>targetFramework="4.6.1"</strong> requestValidationMode="2.0" maxRequestLength="2097151" /&gt;
&lt;authentication mode="Forms"&gt;
<strong>&lt;forms loginUrl="/RHweb_MVC/Seguridad/Login/" protection="All" enableCrossAppRedirects="true" defaultUrl="/RHweb_MVC/" name=".geracauth" timeout="120" path="/" /&gt;</strong>
&lt;/authentication&gt;
</pre>

You had commented the entire forms line. So the name of the cookie was no longer set. And when the targetframework is missing somehow the correct cookie is also not set. By making those 2 changes (uncommenting the `<forms />` & adding `targetFramework="4.6.1"`) Your app will also work for setting the cookie.

**Comment by synercoder** [comment]
Please reopen if it still won't work.
