### ISSUE TITLE
Missing purpose handling

### ISSUE THREAD

**Issue by cveld** [synercoder/FormsAuthentication#5]
We have a legacy ASP.NET Application that also specifies the purpose parameter during encoding:
MachineKey.Protect(bytes, purpose1, purpose2);

Reference source signature:
public static byte[] Unprotect(byte[] protectedData, params string[] purposes)

But your library does not implement the handling of the purposes during decryption:

```
var cryptoProvider = AspNetCryptoServiceProvider.GetCryptoServiceProvider(_options);
var cryptoService = cryptoProvider.GetCryptoService();
byte[] unprotectedData = cryptoService.Unprotect(bytes);
```

There is no purpose / purposes parameter available to apply.

**Comment by synercoder** [comment]
Ill try to look into it somewhere this week, but you may also make the fix yourself and provide a pull request for me.

**Comment by cveld** [comment]
Got it working!

Here is the change set:
![image](https://user-images.githubusercontent.com/6196260/48787657-8b18e600-ece9-11e8-9bd3-41a8b500d9fc.png)

I'll try to create a pull request.
