### ISSUE TITLE
Is there a way to convert ASP.NET Core AuthenticationTicket to a ASP.NET 4 Cookie without changing Startup.cs configuration?

### ISSUE THREAD

**Issue by devrony** [synercoder/FormsAuthentication#9]
Hi,
In my situation, I have a new ASP.NET Core application which needs to generate a Cookie in order to use against an ASP.NET 4 application (not reading a Cookie from ASP.NET 4).  I tried the sample setup you have provided in my ASP.NET Core Startup.cs, which appears to generate a Cookie (which I thought would now be a traditional ASP.NET 4 Cookie using MachineKey in AppSettngs.json).  But when I tried to use it against the ASP.NET 4 application, it appears to not work.   Maybe my assumption is wrong.

What I'd rather do is keep my original setup in ASP.NET Core (using JwtBearer Token) and then within my API controller, generate a valid Forms Auth Cookie for ASP.NET 4.  But not really sure how to accomplish this with the library.  Is this possible?  This is how my legacy code worked in original ASP.NET 4 code:  
`HttpCookie httpCookie = FormsAuthentication.GetAuthCookie(this.UserName, true);  `

I then added this Cookie to the WebRequest object when making a call to the other Web Application.  I've migrated my legacy ASP.NET 4 application to ASP.NET Core but still need to communicate to another ASP.NET 4 application.  User's always log into my ASP.NET Core application, so this is where all the Cookie information be created from.

As always, any help would be appreciated.  
Thanks,
Devaron

**Comment by synercoder** [comment]
You could use the class `FormsAuthenticationCryptor` and then the method `string Protect(FormsAuthenticationCookie cookie)`. That should generate the necessary cookie value. 

Something like:

    public IActionResult Index(
        [FromServices] IHttpContextAccessor httpContextAccessor,
        [FromServices] FormsAuthenticationCryptor formsAuthenticationCryptor)
    {
        var cookieValue = formsAuthenticationCryptor.Protect(new FormsAuthenticationCookie()
        {
            UserName = "",
            IssuedUtc = DateTime.UtcNow,
            ExpiresUtc = DateTime.UtcNow.AddDays(1)
        });

        httpContextAccessor.HttpContext.Response.Cookies.Append("cookieKey", cookieValue);

        return Ok();
    }

Don't forget to setup the DI correctly:

    var section = Configuration.GetSection("FormsAuthentication");
    services.AddSingleton(provider => new FormsAuthenticationOptions()
    {
        DecryptionKey = section.GetValue<string>("DecryptionKey"),
        ValidationKey = section.GetValue<string>("ValidationKey"),
        EncryptionMethod = section.GetValue<EncryptionMethod>("EncryptionMethod"),
        ValidationMethod = section.GetValue<ValidationMethod>("ValidationMethod"),
    });
    services.AddHttpContextAccessor();
    services.AddScoped<FormsAuthenticationCryptor>();

**Comment by synercoder** [comment]
I wrote it quickly, #NotTested but it should get you started.

**Comment by devrony** [comment]
Excellent!  Thank you so much for quick response.  I'll start plugging in now.

**Comment by devrony** [comment]
The code works, but still no luck on the proper Cookie Value being generated.  The legacy ASP.NET Application still rejects it and redirects to the login page.  Just out of curiosity, I see the EncryptionMethod enum doesn't have SHA1?  But in IIS for the legacy ASP.NET application when I look at the Machine Key settings, the Encryption Method field is SHA1.  Also, what Decryption should I use if IIS is "Auto".  AES?  I'm just wondering if I'm setting the wrong values?

```
	public enum EncryptionMethod
	{
		AES = 0,
		TripleDES = 1
	}
```

**Comment by synercoder** [comment]
SHA1 is a hashing method, not a encryption method. So SHA1 is not a valid encryption method.

Could you post your web.config section? (except the machine key itself, just put "abc123" or something in its place).

**Comment by devrony** [comment]
Sorry for the delay, having to jump back to another project constantly :)   I figured the SHA1 was not correct as the Encryption Method based on your code, but seeing in IIS Web App -> Machine Key it says Encryption Method: SHA1.  I was just making sure I wasn't setting my Validation/Encryption Method wrong.  My problem is the Web.config doesn't state what the default is, so I chose AES by default.  Maybe that's my issue?  We don't know which Encryption Method IIS choose?

I've confirmed the IIS Web Apps all share the same Machine Keys (apps hosted on same machine), which match the keys I've setup in appsettings.json file in ASP.NET Core code. 

Also, notice the compatibilityMode="Framework20SP2" in config?  I remember reading something about this somewhere else, but can't remember where.

IIS Web App -> Machine Key Settings
Encryption Method: SHA1
Decryption Method: Auto

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>  
	<system.web>

		<machineKey decryptionKey="BLAHHAHALAHKEY" validationKey="BLAHALAHAHALALAHKEY" />

		<!-- IMPORTANT: Must HAVE in order to support sharing Cookies generated from ASP.NET 4.0 / .NET 4.0 Web Apps -->
    		<httpCookies httpOnlyCookies="true" />
		<machineKey compatibilityMode="Framework20SP2" />

		<httpRuntime executionTimeout="360" maxQueryStringLength="32768" maxRequestLength="2097152" enableVersionHeader="false" />
		<customErrors mode="Off" />
		<httpModules>
			<add name="DomainServiceModule" type="System.ServiceModel.DomainServices.Hosting.DomainServiceHttpModule, System.ServiceModel.DomainServices.Hosting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
		</httpModules>
		<compilation targetFramework="4.5" debug="true">
			<assemblies>
				<add assembly="System.Data.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
			</assemblies>
		</compilation>
		<globalization culture="auto" uiCulture="auto" />
		<authentication mode="Forms">
			<forms name=".BlahBlahCookieName" timeout="480" loginUrl="Login.aspx" domain="blahblahdomain.com" path="/" />
		</authentication>

		<pages controlRenderingCompatibilityVersion="4.0" />

	</system.web>
</configuration>
```

**Comment by synercoder** [comment]
Thanks, Ill see if I can recreate a working sample based upon your config, seems that `compatibilityMode="Framework20SP2"` might be the issue. I based my code on the latest `Framework45` version, because that was what I needed. But currently @ work, so I might be able to whip something up this evening or tomorrow evening.

**Comment by devrony** [comment]
Thanks. I really appreciate the help.  Take your time.  I'm doing some more research on the legacy ASP.NET 4 app around "Roles".  I trying to get access to code and perhaps the page requires a specific role that I'm not applying into the Cookie.UserData.  

Question?  Instead of creating a new FormsAuthenticationCookie, can I convert the existing AuthenticationTicket created by ASP.NET Core, and if so, will that automatically include the existing user's Role information in the Cookie.UserData?  This is how my legacy code was working before.  It created a Cookie based on the authenticated user.

FYI, I tried hard coding the Cookie.UserData value in the code sample you provided above.  Example:  cookie.UserData = "Create Report|View All Data";   Still no luck.  But, I need to confirm what Roles are needed by the legacy ASP.NET 4 application, which I'll do soon.  I'll be out of office today. Back on it tomorrow.

Thanks again.

**Comment by synercoder** [comment]
The roles are not stored in the UserData property, that property is just something you can fill in yourself. Storing the Roles in there could be an implementation details your solution requires, but it is not something the field was designed for originally.

**Comment by devrony** [comment]
Gotcha.  So, how do I add roles?  In the legacy Apps, they both used ASP.NET Membership Providers for authentication/authorization.

**Comment by synercoder** [comment]
It was my understanding that the formsticket contains the username, and the membership provider uses that (unique) username to lookup the user in the db, and find the roles attached.

But again, not currently read up on it anymore, so could be different.

**Comment by devrony** [comment]
Okay, it was my current understanding the cookie value itself had the roles defined in it.  But yes, I'll need to research that on my side.  Been a while since I had to deal with the old Forms Auth with Membership Provider.

**Comment by pkreddy222** [comment]
Do you have a working sample for compatibilityMode="Framework20SP2" or how do we change the compatibilityMode in the code other than the web.config. As my application reads the machineKey data from root application.
Changing in root app is breaking other apps

**Comment by ImGonaRot** [comment]
I too am interested in how to get the web.config setting "Framework20SP2" working.
Our login site requires this setting to work with some of our sub-domains.

**Comment by synercoder** [comment]
It is currently a bit busy on my day job, but ill see if I can dive into these settings in the near future. Till then, PR's are always welcome.

**Comment by ImGonaRot** [comment]
Not sure if posting links to other repos is against the "rules" but here is a link to another repo that works with "Framework20SP2". I have tested it with the current cookies I have and it is working. 

https://github.com/dazinator/AspNetCore.LegacyAuthCookieCompat

**Comment by synercoder** [comment]
There are no rules against sharing good intel :)

**Comment by devrony** [comment]
Excellent. Thanks for posting @ImGonaRot.  My temporary work around was to just leave the old ASP.NET Site up and authenticate to it from my new ASP.NET Core (all 3 sites use the same Membership DB) and store the legacy Cookie as a User Profile Property. Then when I needed to make a request to access the Reporting Site (which uses the legacy Cookie/MachineKey), I could attach the legacy Cookie.  Not ideal, but worked for me in the meantime.  But now I might be able to change over based on the other repo.

**Comment by blieven1** [comment]
> 
> 
> Not sure if posting links to other repos is against the "rules" but here is a link to another repo that works with "Framework20SP2". I have tested it with the current cookies I have and it is working.
> 
> https://github.com/dazinator/AspNetCore.LegacyAuthCookieCompat

This one doesn't work with Framework20SP2, it allready fails on the hash check and doesn't contain 3DES

**Comment by mnoreen** [comment]
@synercoder Not an "issue"... just wanted to put in a good word and thank you for doing this project. I cannot fathom why Microsoft did not provide a simple mechanism like this.  There is a huge .NET Framework base out there, sharing an authentication cookie seems like the only sane way of beginning a migration.  At any rate... thanks.  I hope you are able to continue to update it (say for .NET Core 3 and so on) as time allows you...

**Comment by synercoder** [comment]
Closed because issue contained multiple subjects and inactivity.
